### ISSUE TITLE
Pip-compatible packaging? 

### ISSUE THREAD

**Issue by j4freeman** [tjweisman/geometry_tools#1]
Really awesome work, not seen much else of this quality for visualizing hyperbolic spaces in Python! 

Would be great to get this into a more pip-friendly installation (and maybe even get it on PyPI if you're open to that), had a hard time with the existing setuptools based approach but was able to repackage it to a pip-friendly format pretty easily, more than happy to help with a fork as well!

**Comment by tjweisman** [comment]
thanks, glad people are checking this out! I have been procrastinating putting this up on PyPI solely because I think the project might need a more descriptive name and I don't have one yet...
do you mind letting me know what you needed to change to get this to work with pip? I've only tested installation in pretty limited circumstances, but when I tried, pip worked as-is.
